image: code.lab10.io:4567/graz/10-minerva/minerva-android-v2:builder-v3

before_script:
  - cp ./gradle/wrapper/gradle-wrapper.properties.ci ./gradle/wrapper/gradle-wrapper.properties
  - cp /usr/src/builder/local.properties .  >/dev/null 2>&1 || true

stages:
  - validation
  - distribution
  - update-variable
  - deploy

validateBranch:
  stage: validation
  except:
    refs:
      - master
      - production
  script:
    - java -version
    - ./gradlew test

validateLint:
  stage: validation
  except:
    refs:
      - master
      - production
  script:
    - java -version
    - ./gradlew lint

distributeStagingBuild:
  stage: distribution
  only:
    refs:
      - master

  script:
    - base64 -d $GOOGLE_SERVICES_JSON_BASE64 > MinervaApp/google-services.json
    - base64 -d $KEY_STORE_FILE > MinervaApp/keyStoreMinerva.jks
    - ./gradlew build
    - . /etc/profile.d/rvm.sh
    - fastlane firebaseStaging

  artifacts:
    paths:
      - ./MinervaApp/build/outputs/apk/staging

updateProjectVariable:
  stage: update-variable
  image: curlimages/curl:latest
  only:
    refs:
      - master
  script:
    - |
      curl --silent --show-error --request PUT --header "PRIVATE-TOKEN: $API_TOKEN" "https://code.lab10.io/api/v4/projects/166/variables/VERSION_CODE_STAGING" --form "value=$(($VERSION_CODE_STAGING + 1))"

alphaGooglePlayStore:
  stage: deploy
  only:
    refs:
      - production

  script:
    - base64 -d $GOOGLE_SERVICES_JSON_BASE64 > MinervaApp/google-services.json
    - base64 -d $KEY_STORE_FILE > MinervaApp/keyStoreMinerva.jks
    - ./gradlew build
    - . /etc/profile.d/rvm.sh
    - echo $PLAY_JSON > ./json_file.json
    - fastlane productionAlphaRelease json_path:./json_file.json

  artifacts:
    paths:
      - ./MinervaApp/build/outputs/apk/production
