image: code.lab10.io:4567/graz/10-minerva/minerva-android-v2:builder

variables:
  ANDROID_BUILD_TOOLS: 28.0.2
  ANDROID_HOME: /android-sdk-linux

before_script:
  - cp ./gradle/wrapper/gradle-wrapper.properties.ci ./gradle/wrapper/gradle-wrapper.properties
  - yes | /android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null 2>&1 || true
  - yes | /android-sdk-linux/tools/bin/sdkmanager "build-tools;$ANDROID_BUILD_TOOLS" >/dev/null 2>&1 || true
  - yes | /android-sdk-linux/tools/bin/sdkmanager --licenses >/dev/null 2>&1 || true

stages:
  - validation
  - distribution
  - deploy

validateBranch:
  stage: validation
  except:
    refs:
      - master
  script:
    - ./gradlew test

validateLint:
  stage: validation
  except:
    refs:
      - master
  script:
    - ./gradlew lint

distributeStagingBuild:
  stage: distribution
  only:
    refs:
      - master

  script:
    - base64 -d $KEY_STORE_FILE > MinervaApp/keyStoreMinerva.jks
    - ./gradlew build
    - . /etc/profile.d/rvm.sh
    - ./BuildScripts/build_fastlane.sh
    - fastlane firebaseStaging
    - 'curl --silent --show-error --request PUT --header "PRIVATE-TOKEN: $API_TOKEN" "https://code.lab10.io/api/v4/projects/166/variables/VERSION_CODE_STAGING" --form "value=$(($VERSION_CODE_STAGING + 1))"'

  artifacts:
    paths:
      - ./MinervaApp/build/outputs/apk/staging

#Delete when releasing to production
deployProductionBuild:
  stage: distribution
  only:
    refs:
      - production

  script:
    - base64 -d $KEY_STORE_FILE > MinervaApp/keyStoreMinerva.jks
    - ./gradlew build
    - ./etc/profile.d/rvm.sh
    - ./BuildScripts/build_fastlane.sh
    - echo $PLAY_JSON > ./json_file.json
    - fastlane productionBetaRelease json_path:./json_file.json

  artifacts:
    paths:
      - ./MinervaApp/build/outputs/apk/production

#Uncomment when production app is ready, to upload every new version automatically. Check if the Google Play credential file is needed at this stage ?
#productionReleaseBuild:
#  stage: diploy
#  only:
#    refs:
#      - production
#
#  script:
#  - base64 -d $KEY_STORE_FILE > MinervaApp/keyStoreMinerva.jks
#    - ./gradlew build
#    - . /etc/profile.d/rvm.sh
#    - ./BuildScripts/build_fastlane.sh
#    - fastlane productionRelease
#    - 'curl --silent --show-error --request PUT --header "PRIVATE-TOKEN: $API_TOKEN" "https://code.lab10.io/api/v4/projects/166/variables/VERSION_CODE_STAGING" --form "value=$(($VERSION_CODE_STAGING + 1))"'
#
#  artifacts:
#    paths:
#      - ./MinervaApp/build/outputs/apk/production