on:
  push:
    branches: develop
#    [master, production]

jobs:
  assembleRelease:
    name: restoreReleaseKeystore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "$KEY_STORE_FILE" > keyStoreMinerva.jks.b64
          base64 -d -i keyStoreMinerva.jks.b64 > keyStoreMinerva.jks

