# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

 desc "Submit a new Beta Build to Firebase app distribution"
  lane :firebaseStaging do
    gradle(task: "clean assembleStagingRelease")
    firebase_app_distribution(
               app: "1:927787980045:android:face23e164b9ba95d00c44",
               apk_path: "./MinervaApp/build/outputs/apk/staging/release/MinervaApp-staging-release.apk",
               release_notes: "New stating build in da house, yo!",
               firebase_cli_token: "#{ENV['FIREBASE_TOKEN']}",
               groups:  "minerva_testers")
           slack(
             message: "Fresh and funky staging build is in da house!",
             channel: "#minerva_wallet_status",
             slack_url: "https://hooks.slack.com/services/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",
                )
  end

  desc "Submit a new Production Beta Build to Firebase app distribution"
    lane :firebaseProduction do
      gradle(task: "clean assembleProductionRelease")
      firebase_app_distribution(
                 app: "1:927787980045:android:8c24b855de1a4c03d00c44",
                 apk_path: "./MinervaApp/build/outputs/apk/production/release/MinervaApp-production-release.apk",
                 release_notes: "New production build in da house, yo!",
                 firebase_cli_token: "#{ENV['FIREBASE_TOKEN']}",
                 groups:  "minerva_testers")
             slack(
               message: "Fresh and funky production build is in da house!",
               channel: "#minerva_wallet_status",
               slack_url: "https://hooks.slack.com/services/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",
                  )
    end

  desc "Deploy a Production Build to Beta Channel"
    lane :productionBetaRelease do
      gradle(task: "clean assembleProductionRelease")
      upload_to_play_store(
      track: 'beta',
      json_key: options[:json_path]
      )
             slack(
               message: "Fresh and funky production build is deployed to BETA channel!",
               channel: "#minerva_wallet_status",
               slack_url: "https://hooks.slack.com/services/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",
                  )
    end

  desc "Deploy a Production Build to Google Play Store"
        lane :productionRelease do
          gradle(task: "clean assembleProductionRelease")
          upload_to_play_store
                 slack(
                   message: "Fresh and funky production build is deployed!",
                   channel: "#minerva_wallet_status",
                   slack_url: "https://hooks.slack.com/services/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",
                      )
        end
end